PRT-1046 Adding error handling and timeout parsing for better UX for the user.
lavanet/lava pull request #1048
Opened 2023-12-14 17:34 UTC by ranlavanet

2023-12-17 11:04 UTC, omerlavanet requested changes

2023-12-17 11:04 UTC, omerlavanet commented on protocol/rpcconsumer/relay_errors.go
> +	if errorCount > (len(r.relayErrors) / 2) {
greater equal

2023-12-17 13:51 UTC, ranlavanet commented on protocol/lavasession/consumer_session_manager.go
> +			providerStakeSize, err := consumerSessionsWithProvider.addUsedComputeUnitsAndReturnProviderStakeSize(cuNeededForSession, virtualEpoch)
done 91ae92e541b31c2c6b47689659f2b69268691876

2023-12-17 13:58 UTC, ranlavanet commented on protocol/lavasession/consumer_types.go
> +	return cswp.StakeSize, nil
needs to be locked. fixed here: 9b7fb7060800aa00ed5565f8e0f64dfbc56ddc7c

2023-12-17 14:08 UTC, ranlavanet commented on protocol/lavasession/consumer_session_manager.go
> +						sessionInfo.QoSSummeryResult = github_com_cosmos_cosmos_sdk_types.ZeroDec()
Solved here: e1ca02104bfee61ef320d3b3c53c8f828dc682a3

2023-12-17 14:25 UTC, ranlavanet commented on protocol/rpcconsumer/relay_errors.go
> +func (r *RelayErrors) findLargestValueInMap(myMap map[string]int) (string, int) {
fixed here: 16e01cd8e598dc6a59a5b4c47ac0c9a729512d07

2023-12-17 14:25 UTC, ranlavanet commented on protocol/rpcconsumer/relay_errors.go
> +	if errorCount > (len(r.relayErrors) / 2) {
fixed here: 16e01cd8e598dc6a59a5b4c47ac0c9a729512d07

2023-12-18 09:06 UTC, omerlavanet approved these changes

2023-12-18 09:06 UTC, merged