Cns 786 spec readme
lavanet/lava pull request #1069
Opened 2023-12-26 15:19 UTC by Yaroms

2023-12-26 16:24 UTC, oren-lava requested changes

2023-12-26 16:24 UTC, oren-lava commented on x/spec/README.md
> +A chain spec consists of general properties of the chain and a list of interface it supports. To make specs simple to create and maintain specs can import api's from another, for example, X testnet s
AI:

A chain spec consists of general properties of the chain and a list of interfaces it supports. To simplify the creation and maintenance of specs, they can import APIs from another spec. For example, the X testnet spec can import from the X mainnet spec, eliminating the need to redefine all of the interfaces.

2023-12-26 16:24 UTC, oren-lava commented on x/spec/README.md
> +Note, the `Dec` type is from Cosmos-SDK math LegacyDec.
from Cosmos-SDK math module `LegacyDec` (added backticks to look like code)

2023-12-26 16:24 UTC, oren-lava commented on x/spec/README.md
> +	Index                         string                // chain index (index key for the chain)
chain index (index key for the chain) -> chain unique index

2023-12-26 16:24 UTC, oren-lava commented on x/spec/README.md
> +Note, the `Dec` type is from Cosmos-SDK math LegacyDec.
put extra line between the "Note" sentences to make it appear as a new line. Also, in the second "Note" I would replace it with: "Also" or "Also note"

2023-12-26 16:24 UTC, oren-lava commented on x/spec/README.md
> +    AllowedBlockLagForQosSync     int64                 // defines the accepted blocks a provider can be behind the chain without QOS degradation
align to other fields (see README preview)

2023-12-26 16:24 UTC, oren-lava commented on x/spec/README.md
> +	DataReliabilityEnabled        bool                  // enables/disables data reliability for the chain
align to other fields (see README preview)

2023-12-26 16:24 UTC, oren-lava commented on x/spec/README.md
> +	Enabled                       bool                  // spec enabled/disable (base specs are usually disabled, like cosmos base specs)
parentheses in the comment is irrelevant

2023-12-26 16:24 UTC, oren-lava commented on x/spec/README.md
> +	ApiCollections                []*ApiCollection      // list of ApiCollections that defines all the interfaces and api's of the chain
api's -> APIs

2023-12-26 16:24 UTC, oren-lava commented on x/spec/README.md
> +	ProvidersTypes                Spec_ProvidersTypes   // determines if the spec is for lava or others
others? what others?
can you elaborate below the struct?

2023-12-26 16:24 UTC, oren-lava commented on x/spec/README.md
> +	Contributor                   []string              // list of contributers (public lava address {lava@...})
you did not define anywhere what a contributor is

2023-12-26 16:24 UTC, oren-lava commented on x/spec/README.md
> +	BlockDistanceForFinalizedData uint32
no explanation for finalization fields

2023-12-26 16:24 UTC, oren-lava commented on x/spec/README.md
> +type Spec struct {
The usual format is "struct X" and not "type X struct". I thought it's more readable

2023-12-26 16:24 UTC, oren-lava commented on x/spec/README.md
> +The plans module does not contain parameters.
plans -> spec

2023-12-26 16:24 UTC, oren-lava commented on x/spec/README.md
> +The plans module supports the following queries:
plans -> spec

2023-12-26 16:24 UTC, oren-lava commented on x/spec/README.md
> +The plans module does not support any transactions.
plans -> spec

2023-12-26 16:24 UTC, oren-lava commented on x/spec/README.md
> +The plans module provides a proposal to add/overwrite a spec to the chain
plans -> spec

2023-12-26 16:24 UTC, oren-lava commented on x/spec/README.md
> +    ReliabilityThreshold          uint32                // this determines the amount of data reliability for the chain
what is "amount of data reliability"?

2023-12-31 12:01 UTC, oren-lava requested changes

2023-12-31 12:01 UTC, oren-lava commented on x/spec/README.md
> +| `spec_refresh`    | a spec was redreshed since it had a imported spec modified|
redreshed -> refreshed

2023-12-31 12:19 UTC, Yaroms commented on x/spec/README.md
> +| `spec_refresh`    | a spec was redreshed since it had a imported spec modified|
done

2023-12-31 12:20 UTC, Yaroms commented on x/spec/README.md
> +CollectionData defines the api properties and acts as a unique key for the [api collection](#apicollection)
done

2023-12-31 12:20 UTC, Yaroms commented on x/spec/README.md
> +The `AddOn` field lets you use additional optional APIs like debug, trace,
done

2023-12-31 12:23 UTC, Yaroms commented on x/spec/README.md
> +ParseDirective is a struct that defines a function needed by the provider in a generic way. it describes how for a specific api collection how to get information from the node. for example, how to ge
will do

2023-12-31 12:28 UTC, Yaroms commented on x/spec/README.md
> +	ParseDirectives []*[ParseDirective](#parsedirective)   // list of parsing instructions of specific api's
done

2023-12-31 12:40 UTC, Yaroms commented on x/spec/README.md
> +	Headers         []*Header           // list of headers supported by the interface and their behaviour
done

2023-12-31 13:42 UTC, Yaroms commented on x/spec/README.md
> +	BlockParsing      BlockParser   // specify how to parse the block from the api request
done

2023-12-31 13:48 UTC, Yaroms commented on x/spec/README.md
> +	Extensions      []*Extension        // list of extensions that providers can support in addition to the basic behaviour (for example, archive node)
done

2023-12-31 14:16 UTC, oren-lava approved these changes

2023-12-31 14:29 UTC, merged