PRT-1113 Fixing transactions returning on first error instead of waiting for the result
lavanet/lava pull request #1196
Opened 2024-02-06 18:34 UTC by ranlavanet

2024-02-07 13:41 UTC, omerlavanet requested changes

2024-02-07 13:41 UTC, omerlavanet commented on protocol/rpcconsumer/rpcconsumer_server.go
> +	go rpccs.getBestResult(result, relayTimeout, responses, len(sessions), chainMessage)
this is a go routine with a blocking channel after, there's no need for that, just check the stuff in a sync function, and continue when it returns

2024-02-07 13:41 UTC, omerlavanet commented on protocol/rpcconsumer/rpcconsumer_server.go
> +	getBestResponseBetweenNodeAndProtocolErrors := func() error {
just return two args here instead

2024-02-07 13:41 UTC, omerlavanet commented on protocol/rpcconsumer/rpcconsumer_server.go
> +func (rpccs *RPCConsumerServer) getBestResult(finalResult chan *relayResponse, timeout time.Duration, responses chan *relayResponse, numberOfSessions int, chainMessage chainlib.ChainMessage) {
instead of getting the channel as input just return the value you write to it as a returned value

2024-02-07 13:41 UTC, omerlavanet commented on protocol/rpcconsumer/rpcconsumer_server.go
> +				utils.LavaFormatDebug("no protocol error", utils.LogAttr("Status code", response.relayResult.StatusCode))
pretty spammy, maybe combine to one message what you need?

2024-02-07 13:41 UTC, omerlavanet commented on protocol/rpcconsumer/rpcconsumer_server.go
> +					utils.LavaFormatDebug("returned result")
remove

2024-02-07 13:41 UTC, omerlavanet commented on protocol/rpcconsumer/rpcconsumer_server.go
> +		if len(nodeResponseErrors.relayErrors) > 0 { // if we have node errors, we prefer returning them over protocol errors.
good job, smart

2024-02-07 13:41 UTC, omerlavanet commented on protocol/rpcconsumer/rpcconsumer_server.go
> +			// (wether its a node error or protocol errors)
whether

2024-02-08 08:18 UTC, omerlavanet requested changes

2024-02-08 09:16 UTC, ranlavanet commented on protocol/rpcconsumer/relay_errors.go
>  		errorMessage := relayError.err.Error()
this is mostly for node messages. and they should be deterministic

2024-02-08 11:12 UTC, omerlavanet approved these changes

2024-02-08 11:12 UTC, merged