Add specs: Blast Sepolia
lavanet/lava pull request #1236
Opened 2024-02-18 16:08 UTC by AsharibAli

2024-02-20 08:47 UTC, omerlavanet requested changes
please attach the result of scripts/test_spec_full.sh with the spec file to the PR

2024-02-20 08:47 UTC, omerlavanet commented on cookbook/specs/spec_add_blast.json
> +                    "latest_distance": 1024
this means any query 1025+ blocks in the past will either need to go to archive or fail, our usual rule of thumb is 24h of blocks so 24*3600/averageBlockTime(s)

2024-02-21 16:41 UTC, AsharibAli commented
@omerlavanet can you please look at it, brother!

2024-02-21 20:20 UTC, omerlavanet commented
> please attach the result of scripts/test_spec_full.sh with the spec file to the PR

have you tested it?

2024-02-21 20:23 UTC, omerlavanet submitted a review, later dismissed
looks good, just missing the rule fix and attaching the script run result to showcase it worked

2024-02-21 20:23 UTC, omerlavanet commented on cookbook/specs/spec_add_blast.json
> +                  "block": 2048
this is still directing traffic to archive pretty quickly,
it's usually pruning latest distance-3%

2024-02-22 06:21 UTC, AsharibAli commented
> have you tested it?

Could you please test it for me, I'm having some problems in my dev environment!

2024-02-23 13:31 UTC, AsharibAli commented
@omerlavanet please test the following, if your environment is ready for testing, I'm having some issues!

2024-02-28 12:48 UTC, merged