PRT-1166 cache hash key migration. (WIP)
lavanet/lava pull request #1300
Opened 2024-03-13 17:41 UTC by ranlavanet

2024-03-17 20:10 UTC, omerlavanet requested changes

2024-03-17 20:10 UTC, omerlavanet commented on protocol/rpcprovider/rpcprovider_server.go
> +					OptionalMetadata: ignoredMetadata,
you forgot average block time and seen block

2024-03-17 20:10 UTC, omerlavanet commented on protocol/rpcprovider/rpcprovider_server.go
> +				Finalized:      finalized,
seen block missing here

2024-03-17 20:11 UTC, omerlavanet requested changes
let's add the following test too:
set up a provider, cache using chainFetcher, see that we hit the cache by requesting from a user (with seen block)

2024-03-18 09:47 UTC, ranlavanet commented on protocol/rpcprovider/rpcprovider_server.go
> +				Finalized:      finalized,
agreed that its ok.

2024-03-18 16:55 UTC, omerlavanet approved these changes

2024-03-18 16:55 UTC, merged