feat: CNS-950-celestia-spec
lavanet/lava pull request #1401
Opened 2024-05-01 15:23 UTC by Yaroms

2024-05-01 15:35 UTC, oren-lava requested changes

2024-05-01 15:35 UTC, oren-lava commented on scripts/init_chain_commands.sh
> +CHAINS="ETH1,SEP1,HOL1,OSMOSIS,FTM250,CELO,LAV1,OSMOSIST,ALFAJORES,ARB1,ARBN,APT1,STRK,JUN1,COSMOSHUB,POLYGON1,EVMOS,OPTM,BASES,CANTO,SUIT,SOLANA,BSC,AXELAR,AVAX,FVM,NEAR,SQDSUBGRAPH,AGR,AGRT,KOIIT,A
also update setup_providers.sh and full_consumer_example.yml for mocha

2024-05-05 10:38 UTC, oren-lava submitted a review, later dismissed

2024-05-05 10:45 UTC, omerlavanet requested changes

2024-05-05 10:45 UTC, omerlavanet commented on cookbook/specs/spec_add_celestia.json
> +                                    "parser_func": "DEFAULT"
parser is wrong

2024-05-05 10:46 UTC, omerlavanet requested changes

2024-05-05 10:46 UTC, omerlavanet commented on cookbook/specs/spec_add_celestia.json
> +                                    "parser_func": "DEFAULT"
wrong parser

2024-05-05 14:07 UTC, omerlavanet approved these changes

2024-05-05 14:31 UTC, merged