CNS-955: add provider description and spec identity
lavanet/lava pull request #1433
Opened 2024-05-12 15:05 UTC by oren-lava

In this PR, I added new fields to the stake entry struct and spec struct.

For the stake entry, I added the a description field of the Staking module's type Description. This new field replaces the moniker field. Also, I implemented a migrator that populated the new description field with the old moniker. The migrator was tested on testnet successfully.

For the spec, I added an identity field.

2024-05-15 10:34 UTC, Yaroms commented on x/pairing/types/message_stake_provider.go
> -	if len(msg.Moniker) > MAX_LEN_MONIKER {
validate description

2024-05-19 14:41 UTC, oren-lava commented on x/pairing/types/message_stake_provider.go
> -	if len(msg.Moniker) > MAX_LEN_MONIKER {
done. see https://github.com/lavanet/lava/commit/44fa0e05fafba5cf83e6def25c4262a30f490b08

2024-05-23 08:32 UTC, omerlavanet requested changes

2024-05-27 07:51 UTC, oren-lava commented on x/pairing/types/message_stake_provider.go
> +// TODO: add validation to new fields
done. see https://github.com/lavanet/lava/commit/f8e6295f437300f6f6d7317b537919606dae7a3a

2024-05-27 07:51 UTC, oren-lava commented on x/pairing/keeper/unstaking.go
> -		"moniker":     existingEntry.GetMoniker(),
done. see https://github.com/lavanet/lava/commit/f8e6295f437300f6f6d7317b537919606dae7a3a

2024-05-27 07:51 UTC, oren-lava commented on x/pairing/keeper/unstaking.go
> -				"moniker":     existingEntry.GetMoniker(),
done. see https://github.com/lavanet/lava/commit/f8e6295f437300f6f6d7317b537919606dae7a3a

2024-05-27 07:51 UTC, oren-lava commented on x/pairing/keeper/staking.go
> -	details = append(details, utils.Attribute{Key: "moniker", Value: moniker})
done. see https://github.com/lavanet/lava/commit/f8e6295f437300f6f6d7317b537919606dae7a3a

2024-05-27 07:51 UTC, oren-lava commented on x/pairing/keeper/staking.go
> -		details = append(details, utils.Attribute{Key: "moniker", Value: moniker})
done. see https://github.com/lavanet/lava/commit/f8e6295f437300f6f6d7317b537919606dae7a3a

2024-05-27 12:55 UTC, Yaroms approved these changes

2024-05-27 12:56 UTC, merged