feat: dymension
lavanet/lava pull request #1473
Opened 2024-06-04 08:21 UTC by BabyScope

changed name of dymension

2024-07-01 08:50 UTC, omerlavanet requested changes

2024-07-01 08:50 UTC, omerlavanet commented on cookbook/specs/dymension.json
> +                      "expected_value": ""
why an empty expected value?

2024-07-01 08:50 UTC, omerlavanet commented on cookbook/specs/dymension.json
> +                      "expected_value": ""
same q

2024-07-01 11:21 UTC, BabyScope commented on cookbook/specs/dymension.json
> +                      "expected_value": ""
this was a mistake.

2024-07-01 11:21 UTC, BabyScope commented on cookbook/specs/dymension.json
> +                      "expected_value": ""
solved it

2024-11-12 13:57 UTC, closed without merging

2024-11-12 13:57 UTC, Yaroms commented
currently not needed, thanks for the work