feat: Reputation: CNS-1003: reputation proto definitions
lavanet/lava pull request #1604
Opened 2024-08-01 08:39 UTC by oren-lava

# Description

Closes: #XXXX

Implemented the required proto types for the reputation feature.

---

## Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

* [ ] read the [contribution guide](https://github.com/lavanet/lava/blob/main/CONTRIBUTING.md)
* [ ] included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title, you can find examples of the prefixes below:
    
* [ ] confirmed `!` in the type prefix if API or client breaking change
* [ ] targeted the `main` branch
* [ ] provided a link to the relevant issue or specification
* [ ] reviewed "Files changed" and left comments if necessary
* [ ] included the necessary unit and integration tests
* [ ] updated the relevant documentation or specification, including comments for [documenting Go code](https://blog.golang.org/godoc)
* [ ] confirmed all CI checks have passed

## Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*

I have...

* [ ] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
* [ ] confirmed all author checklist items have been addressed
* [ ] reviewed state machine logic, API design and naming, documentation is accurate, tests and test coverage

2024-12-25 13:58 UTC, omerlavanet requested changes

2025-01-05 12:09 UTC, oren-lava commented on testutil/e2e/protocolE2E.go
> +		"%s/lavanet/lava/v2/pairing/providers/LAV1",
done. see https://github.com/lavanet/lava/commit/62eb5c0de131129cd989368f440e61e6a78492c5

2025-01-05 12:10 UTC, oren-lava commented on x/pairing/keeper/reputation.go
> +	return qos, nil
done. see https://github.com/lavanet/lava/commit/62eb5c0de131129cd989368f440e61e6a78492c5
I put dummy values because the original implementation relied on `providerQosFs` which doesn't exist anymore.

2025-01-06 12:52 UTC, Yaroms commented on x/pairing/keeper/keeper.go
> +		reputations       collections.Map[collections.Triple[string, string, string], types.Reputation] // save qos info per provider, chain and cluster
fix the comment about the order of the key

2025-01-06 12:54 UTC, Yaroms commented on x/pairing/keeper/reputation.go
> +func (k Keeper) GetQos(ctx sdk.Context, chainID string, cluster string, provider string) (qos types.QualityOfServiceReport, err error) {
change the method name to reputationScore

2025-01-07 09:32 UTC, oren-lava commented on x/pairing/keeper/keeper.go
> +		reputations       collections.Map[collections.Triple[string, string, string], types.Reputation] // save qos info per provider, chain and cluster
done. see https://github.com/lavanet/lava/commit/0ccad7cd3e2a2142e3bafefa775e61c0e6b7f688

2025-01-07 14:18 UTC, oren-lava commented on x/pairing/types/reputation.go
> +func ReputationKey(chainID string, cluster string, provider string) collections.Triple[string, string, string] {
the new reputations fixation store uses the same prefix as the old one, so no migrator needed

2025-01-12 08:44 UTC, Yaroms commented on x/pairing/keeper/keeper.go
> +		pairingQueryCache *map[string][]epochstoragetypes.StakeEntry
didnt we delete this?

2025-01-12 11:41 UTC, oren-lava commented on x/pairing/keeper/keeper.go
> +		pairingQueryCache *map[string][]epochstoragetypes.StakeEntry
done. see https://github.com/lavanet/lava/commit/62190435df5f2b33e55bb59192b5bb04fb17e00c

2025-01-19 15:04 UTC, Yaroms approved these changes

2025-01-19 15:05 UTC, merged