feat: GRPC health
lavanet/lava pull request #1690
Opened 2024-09-11 21:42 UTC by amitza

# Description

Closes: #154

Add support for GRPC [health checking](https://github.com/grpc/grpc/blob/master/doc/health-checking.md). This will allow the blackbox exporter to query the GRPC directly.

---

## Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

* [x] read the [contribution guide](https://github.com/lavanet/lava/blob/main/CONTRIBUTING.md)
* [x] included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title, you can find examples of the prefixes below:
    
* [x] confirmed `!` in the type prefix if API or client breaking change
* [x] targeted the `main` branch
* [x] provided a link to the relevant issue or specification
* [x] reviewed "Files changed" and left comments if necessary
* [x] included the necessary unit and integration tests
* [x] updated the relevant documentation or specification, including comments for [documenting Go code](https://blog.golang.org/godoc)
* [x] confirmed all CI checks have passed

## Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*

I have...

* [ ] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
* [ ] confirmed all author checklist items have been addressed
* [ ] reviewed state machine logic, API design and naming, documentation is accurate, tests and test coverage

2024-09-11 22:28 UTC, shleikes requested changes

2024-09-11 22:28 UTC, shleikes commented on protocol/rpcprovider/provider_listener_test.go
> +	}
Use the require lib (don't forget to import it)
```suggestion
    require.NoError(t, err)
```

2024-09-11 22:28 UTC, shleikes commented on protocol/rpcprovider/provider_listener_test.go
> +	}
Same here

2024-09-11 22:28 UTC, shleikes commented on protocol/rpcprovider/provider_listener_test.go
> +		t.Errorf("Unexpected health status: got %v, want %v", resp.Status, grpc_health_v1.HealthCheckResponse_SERVING)
Same here

2024-09-12 09:05 UTC, shleikes approved these changes

2024-09-12 11:15 UTC, omerlavanet approved these changes

2024-09-12 11:18 UTC, merged