feat: PRT - Optimizer metrics - including tiers
lavanet/lava pull request #1701
Opened 2024-09-16 07:57 UTC by shleikes

2024-09-23 15:35 UTC, ranlavanet requested changes

2024-10-10 12:54 UTC, shleikes commented on protocol/lavasession/consumer_session_manager.go
> +			selectionTier, _ := csm.providerOptimizer.CalculateSelectionTiers(csm.validAddresses, nil, 10, spectypes.LATEST_BLOCK)
Fixed in 66f074bd01485842fe48d8868985f25391163666

2024-10-10 14:01 UTC, shleikes commented on protocol/lavasession/consumer_session_manager.go
> +			selectionTier, _ := csm.providerOptimizer.CalculateSelectionTiers(csm.validAddresses, nil, 10, spectypes.LATEST_BLOCK)
Fixed in eacc61bbe2f3edd6e2c67cdeda472711b7d93e48

2024-10-30 17:46 UTC, omerlavanet commented
@shleikes if this is stale please remove the PR

2024-11-14 13:31 UTC, shleikes commented on protocol/lavasession/consumer_session_manager.go
> +	CollectOptimizerProvidersScoreFlagName     = "collect-optimizer-providers-score"
Fixed in 8bde3988f0b52cb9db9ee6c4537f30f23305e9b0

2024-11-14 13:31 UTC, shleikes commented on protocol/lavasession/consumer_session_manager.go
> +	stakeEntriesForMetrics := map[string]uint64{}
Fixed in ee19d51f05192fdafaa745edbbda21cd7c09af60

2024-11-14 13:31 UTC, shleikes commented on protocol/lavasession/consumer_session_manager.go
> +		for _, chosenProvider := range providers {
Fixed in b9d7e5dd81b0a36db54b3d68e185a385b8034e1e

2024-11-14 13:32 UTC, shleikes commented on protocol/lavasession/consumer_session_manager.go
> +		csm.consumerMetricsManager.SetQOSMetrics(chainId, apiInterface, publicProviderAddress, lastQos, lastQosExcellence, consumerSession.LatestBlock, consumerSession.RelayNum, relayLatency, sessionSucces
Fixed in ab36352e952e9032cdc3bb9e7842b9ca1f3701b5

2024-11-14 13:32 UTC, shleikes commented on protocol/lavasession/consumer_session_manager.go
> +				tierEntries := selectionTier.GetTier(i, provideroptimizer.OptimizerNumTiers, 1)
Fixed in b95df52df43c635b5bb8401933d9f1247e4beb82

2024-11-14 13:32 UTC, shleikes commented on protocol/lavasession/consumer_session_manager.go
> +			// collect optimizer providers score
Fixed in 8a21e28d727afd904d259c944c28beb69653de2f

2024-11-14 13:32 UTC, shleikes commented on protocol/lavasession/consumer_session_manager.go
> +			go csm.consumerMetricsManager.UpdateOptimizerProvidersScore(csm.rpcEndpoint.ChainID, csm.rpcEndpoint.ApiInterface, csm.currentEpoch, metricsTiers)
Fixed in 8a21e28d727afd904d259c944c28beb69653de2f

2024-11-26 11:41 UTC, closed without merging