fix: PRT - Replace the method in the debug verification in EVMOS spec
lavanet/lava pull request #1723
Opened 2024-10-01 08:34 UTC by shleikes

2024-10-01 08:38 UTC, Yaroms approved these changes

2024-10-01 08:39 UTC, nimrod-teich requested changes
Add the verification to EVMOST as well.

2024-10-01 09:04 UTC, nimrod-teich approved these changes

2024-10-01 09:14 UTC, Yaroms approved these changes

2024-10-01 11:54 UTC, ranlavanet approved these changes

2024-10-07 12:25 UTC, omerlavanet approved these changes

2024-10-07 12:25 UTC, merged