PRT - Websocket limited per ip
lavanet/lava pull request #1738
Opened 2024-10-11 18:04 UTC by ranlavanet

# Description

Closes: #XXXX

---

## Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

* [ ] read the [contribution guide](https://github.com/lavanet/lava/blob/main/CONTRIBUTING.md)
* [ ] included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title, you can find examples of the prefixes below:
    
* [ ] confirmed `!` in the type prefix if API or client breaking change
* [ ] targeted the `main` branch
* [ ] provided a link to the relevant issue or specification
* [ ] reviewed "Files changed" and left comments if necessary
* [ ] included the necessary unit and integration tests
* [ ] updated the relevant documentation or specification, including comments for [documenting Go code](https://blog.golang.org/godoc)
* [ ] confirmed all CI checks have passed

## Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*

I have...

* [ ] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
* [ ] confirmed all author checklist items have been addressed
* [ ] reviewed state machine logic, API design and naming, documentation is accurate, tests and test coverage

2024-10-13 11:37 UTC, nimrod-teich commented
I wouldn't use the IP alone as the unique identifier to map the open sockets (what happens when users behind NAT are sending requests?). 
A combination of the real IP (extracted from _**X-Forwarded-For**_) and user-agent is adviced.

2024-10-13 12:30 UTC, omerlavanet commented
> I wouldn't use the IP alone as the unique identifier to map the open sockets (what happens when users behind NAT are sending requests?). A combination of the real IP (extracted from _**X-Forwarded-For**_) and user-agent is adviced.

agreed and i would take it a step further, allow a special header to change the rate, and we force set this header on our nginx, because otherwise you have to manage special rate limits within the consumer

2024-10-16 13:22 UTC, ranlavanet commented
@nimrod-teich , @omerlavanet 

I've added a header to rate limit. functionality is quite the same as the flag just here we can control it from ngnix instead of directly in process 

Header name:
WebSocketRateLimitHeader = "x-lava-rate-limit"

Example use:
-H "x-lava-rate-limit: 10" (will result in rate limit of 10 requests per second)

2024-10-30 18:08 UTC, omerlavanet requested changes

2024-10-30 18:08 UTC, omerlavanet commented on protocol/chainlib/websocket_connection_limiter.go
> +		numberOfActiveConnections := wcl.addIpConnectionAndGetCurrentAmount(key)
you add then immediately decrease, and not when the connection is down, no other writes to the active connections, this will always be true

2024-10-30 18:08 UTC, omerlavanet commented on protocol/chainlib/websocket_connection_limiter.go
> +		key := wcl.getKey(ip, ipForwarded)
we said we will do this based on dappId, ip and user agent

2024-12-05 10:07 UTC, shleikes commented on protocol/chainlib/consumer_websocket_manager.go
> +					websocketConn.WriteMessage(websocket.CloseMessage, websocket.FormatCloseMessage(websocket.CloseNormalClosure, fmt.Sprintf("Connection idle for too long, closing connection. Idle time: %d", idleD
Fixed in bc80aa902923edf4daab1ff639bf58b56187fafa

2024-12-05 10:07 UTC, shleikes commented on protocol/chainlib/consumer_websocket_manager.go
> +		idleFor.Store(time.Now().Unix())
Fixed in 7f73f9378792e75e085b12b81bfa026fb02f56b8

2024-12-05 10:07 UTC, shleikes commented on protocol/chainlib/websocket_connection_limiter.go
> +func (wcl *WebsocketConnectionLimiter) handleFiberRateLimitFlags(c *fiber.Ctx) {
Fixed in 52233d5b31efaf904d3ffdc7a603045bb1717dbf

2024-12-05 10:08 UTC, shleikes commented on protocol/chainlib/websocket_connection_limiter.go
> +func (wcl *WebsocketConnectionLimiter) canOpenConnection(websocketConn WebsocketConnection) (bool, func()) {
Fixed in 52233d5b31efaf904d3ffdc7a603045bb1717dbf

2024-12-05 10:08 UTC, shleikes commented on protocol/chainlib/websocket_connection_limiter.go
> +func (wcl *WebsocketConnectionLimiter) addIpConnectionAndGetCurrentAmount(key string) {
Fixed in 52233d5b31efaf904d3ffdc7a603045bb1717dbf

2024-12-05 12:17 UTC, omerlavanet approved these changes

2024-12-05 13:00 UTC, merged