refactor: PRT - Replace cookbook/specs with lava-config specs
lavanet/lava pull request #1813
Opened 2024-12-01 13:53 UTC by shleikes

2024-12-08 12:00 UTC, oren-lava requested changes

2024-12-09 12:35 UTC, shleikes commented on utils/keeper/spec.go
> +	baseProposalFiles := []string{
You're right about ethermint, but why Solana?

2024-12-09 12:36 UTC, shleikes commented on scripts/useful_commands.sh
> +    local priority_specs=(
Why?

2024-12-09 12:38 UTC, shleikes commented on specs/mainnet-1/specs/blast.json
> +{
Will change now, thanks!
I think I'll put the spec that are not deployed anywhere, back into `cookbook/specs`, what do you think?

2024-12-09 12:38 UTC, shleikes commented on x/spec/keeper/spec_test.go
> +func TestMainnetSpecs(t *testing.T) {
Fixed in 379a2d1a152d3e43bdd986f75cec47f8d48379fe

2024-12-09 12:41 UTC, oren-lava commented on utils/keeper/spec.go
> +	baseProposalFiles := []string{
I'm thought that big chains that other specs import are in this category and koii imports solana. Might not be right, so it's not mandatory

2024-12-09 12:43 UTC, oren-lava commented on specs/mainnet-1/specs/blast.json
> +{
Maybe `cookbook/not_deployed`? or add a readme that states:
1. `mainnet` specs are specs that are on both mainnet and testnet
2. `testnet` specs are only on testnet
3. `specs` specs are not deployed

2024-12-09 14:33 UTC, shleikes commented on specs/mainnet-1/specs/blast.json
> +{
Fixed

2024-12-15 12:21 UTC, Yaroms approved these changes

2024-12-15 12:49 UTC, merged