feat: add telegram bot to lavap health
lavanet/lava pull request #1862
Opened 2024-12-22 15:35 UTC by Yaroms

# Description

Closes: #XXXX

---

## Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

* [ ] read the [contribution guide](https://github.com/lavanet/lava/blob/main/CONTRIBUTING.md)
* [ ] included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title, you can find examples of the prefixes below:
    
* [ ] confirmed `!` in the type prefix if API or client breaking change
* [ ] targeted the `main` branch
* [ ] provided a link to the relevant issue or specification
* [ ] reviewed "Files changed" and left comments if necessary
* [ ] included the necessary unit and integration tests
* [ ] updated the relevant documentation or specification, including comments for [documenting Go code](https://blog.golang.org/godoc)
* [ ] confirmed all CI checks have passed

## Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*

I have...

* [ ] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
* [ ] confirmed all author checklist items have been addressed
* [ ] reviewed state machine logic, API design and naming, documentation is accurate, tests and test coverage

2024-12-23 11:36 UTC, shleikes requested changes

2024-12-23 11:36 UTC, shleikes commented on protocol/monitoring/alerting.go
> +	TelegramAlerting              TelegramAlertingOptions
Why are you inherit and holding a TelegramAlertingOptions?

2024-12-23 11:36 UTC, shleikes commented on protocol/monitoring/health_cmd.go
> +	telegramChannelIDFlagName            = "telegram-channel-id"
Change to `telegram-alert-bot-token` and `telegram-alert-channel-id`

2024-12-23 11:36 UTC, shleikes commented on protocol/monitoring/health_cmd.go
> +	cmdTestHealth.Flags().String(telegramChannelIDFlagName, "", "telegram channel ID where alerts will be sent (must start with -100)")
I don't see where do you read this flag

2024-12-23 11:36 UTC, shleikes commented on protocol/monitoring/alerting.go
> +	}
You check this inside `SendTelegramAlert`

2024-12-23 11:36 UTC, shleikes commented on protocol/monitoring/alerting.go
> +		al.SendTelegramAlert(alert, attrs)
You don't do anything with the returned error?

2024-12-23 11:36 UTC, shleikes commented on protocol/monitoring/telegram_alerting.go
> +	defer resp.Body.Close()
Move the defer to line 48, right after `resp, err := http.Post(url ...`

2024-12-23 11:36 UTC, shleikes commented on protocol/monitoring/telegram_alerting_test.go
> +			},
Why is this here and not inside the test itself?

2024-12-23 11:36 UTC, shleikes commented on protocol/monitoring/telegram_alerting_test.go
> +				assert.NoError(t, err)
Use require instead of assert

2025-01-13 12:05 UTC, Yaroms commented on protocol/monitoring/telegram_alerting_test.go
> +				assert.NoError(t, err)
done

2025-01-13 12:06 UTC, Yaroms commented on protocol/monitoring/alerting.go
> +	}
done

2025-01-13 12:10 UTC, Yaroms commented on protocol/monitoring/health_cmd.go
> +	telegramChannelIDFlagName            = "telegram-channel-id"
done

2025-01-13 12:10 UTC, Yaroms commented on protocol/monitoring/health_cmd.go
> +	cmdTestHealth.Flags().String(telegramChannelIDFlagName, "", "telegram channel ID where alerts will be sent (must start with -100)")
added

2025-01-13 12:12 UTC, Yaroms commented on protocol/monitoring/telegram_alerting.go
> +	defer resp.Body.Close()
this is wrong since if returns an error resp is nil

2025-01-13 12:13 UTC, Yaroms commented on protocol/monitoring/telegram_alerting_test.go
> +			},
since not all scenatious need to check the request

2025-01-13 12:29 UTC, Yaroms commented on protocol/monitoring/alerting.go
> +	TelegramAlerting              TelegramAlertingOptions
why not?

2025-01-13 12:43 UTC, shleikes approved these changes

2025-01-13 12:43 UTC, shleikes commented on protocol/monitoring/alerting.go
> +	TelegramAlerting              TelegramAlertingOptions
Me stupid, you ignore

2025-02-02 17:47 UTC, ranlavanet approved these changes

2025-02-02 17:48 UTC, merged