PRT 201 verify why e2e didn't discover the payments bug
lavanet/lava pull request #213
Opened 2022-12-29 12:18 UTC by kajeagentspi

This PR adds error allowlist to e2e.

2023-01-02 17:54 UTC, Aleksao998 submitted a review, later dismissed
LGTM, Thank you for opening this PR 🚀 Please check these small nitpicks

2023-01-05 09:58 UTC, Aleksao998 requested changes
Leaving request changes no to merge this PR till we rename whitelist -> allowlist to all places.
Overall PR looks good 🚀

2023-01-06 03:10 UTC, kajeagentspi commented on testutil/e2e/e2e.go
>  			fmt.Println(err)
Changed to MkdirAll so no errors would be thrown when folder already exists. If there are some errors aside from that it would panic now.

2023-01-06 03:11 UTC, kajeagentspi commented
Changed all whitelist to allow let me know if I missed some.

2023-01-09 05:53 UTC, Aleksao998 requested changes

2023-01-09 05:53 UTC, Aleksao998 commented on testutil/e2e/README.md
> +# Error Whitelist
Can we rename whitelist -> allowlist

2023-01-09 05:53 UTC, Aleksao998 commented on testutil/e2e/README.md
> +The error whitelist contains a list of errors that is allowed to happen during tests. The key is the error substring that can be seen in the logs. The value is the description on why this error is wh
Also here we have whitelist which needs to be replaced with allow-list

2023-01-09 20:25 UTC, Aleksao998 approved these changes
Thank you for resolving all comments 🚀

2023-01-10 16:46 UTC, merged