PRT-227 refactor chain sentry class
lavanet/lava pull request #218
Opened 2023-01-02 19:19 UTC by theinterestedr1

2023-01-10 21:27 UTC, ranlavanet requested changes

2023-01-10 21:27 UTC, ranlavanet commented on relayer/chainTracker/errors.go
> +	InvalidConfigBlockTime          = sdkerrors.New("Invalid average block time", 2, "average block time wasn't defined in config")
Lets create a more unique errors, 1 digit might overlap with other errors we can go 6 digit errors

2023-01-11 17:16 UTC, omerlavanet commented on relayer/chainTracker/chainTracker.go
> +	return cs.blocksQueue[0]
there's a check literally one line before the only call of this function, the reason i moved it to a function is readability, and i also marked it unsafe we were good

2023-01-11 17:17 UTC, omerlavanet commented on relayer/chainTracker/chainTracker.go
> +	if len(cs.blocksQueue) == 0 {
no need to verify lock on internal unexposed functions

2023-01-11 18:57 UTC, ranlavanet approved these changes

2023-01-11 18:57 UTC, merged