Send uri request over http not rpc
lavanet/lava pull request #247
Opened 2023-01-21 10:08 UTC by Aleksao998

* **Please check if the PR fulfills these requirements**
- [ ] Commit message follows the Contribution Guidelines
- [ ] Tests ran locally and added/modified if needed
- [ ] Docs have been added/updated, if applicable
- [ ] If applicable - JIRA ticket ID was added

* **What kind of change does this PR introduce?** (Bug fix, feature, unit tests, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Please describe what manual tests you ran, if applicable**

* **Other information**:

2023-01-29 11:11 UTC, ranlavanet requested changes

2023-01-29 11:11 UTC, ranlavanet commented on proto/spec/service_api.proto
> +  BlockParser overwrite_block_parsing = 4;
dont forget to regenrate the proto files after

2023-01-30 09:16 UTC, Aleksao998 commented on proto/spec/service_api.proto
> +  BlockParser overwrite_block_parsing = 4;
Fixed 52684875607c3536b995ae8cabe7f992d8df89f1

2023-02-01 10:27 UTC, omerlavanet commented on relayer/parser/parser.go
> +		value := parseArrayOfInterfaces(unmarshalledDataTyped, propName, innerSeparator)
well done!

2023-02-01 10:28 UTC, omerlavanet approved these changes
recent main changes to tendermint would not be introduced on the RUI path, need to manually merge

2023-02-01 10:29 UTC, merged