CNS-169: create module subscription
lavanet/lava pull request #328
Opened 2023-02-28 11:44 UTC by orenl-lava

This PR holds the the result of the scaffolding module subscription.

The code was auto-generated using:
```ignite scaffold module subscription```
Pushed in a separate PR to simplify the review of the upcoming changes.

* **Please check if the PR fulfills these requirements**
- [x] Commit message follows the Contribution Guidelines
- [x] Tests ran locally and added/modified if needed
- [x] Docs have been added/updated, if applicable
- [x] If applicable - JIRA ticket ID was added

* **What kind of change does this PR introduce?** (Bug fix, feature, unit tests, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Please describe what manual tests you ran, if applicable**

* **Other information**:

2023-02-28 12:53 UTC, Yaroms requested changes
scaffold generated files not always follow our linter rules.
please go over those errors and fix the linter issues, if we dont do that main will break

2023-03-02 05:57 UTC, orenl-lava commented
> scaffold generated files not always follow our linter rules.
> please go over those errors and fix the linter issues, if we dont do that main will break

done.

2023-03-02 08:38 UTC, Yaroms submitted a review, later dismissed

2023-03-03 17:17 UTC, Yaroms approved these changes

2023-03-03 17:17 UTC, merged