Cns 288 create basic pairing of project providers
lavanet/lava pull request #358
Opened 2023-03-15 13:12 UTC by Yaroms

2023-03-15 18:15 UTC, omerlavanet requested changes
NICE JOB!

2023-03-15 18:15 UTC, omerlavanet commented on x/pairing/keeper/pairing_subscription_test.go
> +				Provider:        ts.providers[0].address.String(),
this is incompatible with how we build relays after the change, and creating the object with the keys like that leaves a lof ot lines to be changed, and i am tired already of manually changing how it's done with copy paste in all of our unitests, use a common function to build stub relays please

2023-03-15 18:15 UTC, omerlavanet commented on x/projects/keeper/project.go
> +	if project.Policy.TotalCuLimit <= project.UsedCu {
use a method

2023-03-16 09:53 UTC, omerlavanet commented on x/pairing/keeper/msg_server_relay_payment_test.go
created a task for it

2023-03-16 13:05 UTC, omerlavanet approved these changes

2023-03-16 16:13 UTC, omerlavanet approved these changes

2023-03-16 16:36 UTC, orenl-lava commented on proto/pairing/query.proto
> +  uint64 pairedProviders = 3;
nit: isn't the coding style in *.proto files like "paired_providers"?
and also "cu_per_epoch" below?

2023-03-16 17:32 UTC, omerlavanet commented on proto/projects/project.proto
> +    string projectID = 1;
we need to align all ID, let's do it in a separate PR

2023-03-16 17:34 UTC, omerlavanet approved these changes

2023-03-16 17:46 UTC, merged