Cns-397 vrf removal implement
lavanet/lava pull request #477
Opened 2023-05-09 13:55 UTC by ranlavanet

2023-05-10 15:12 UTC, omerlavanet commented on protocol/lavaprotocol/request_builder.go
> +		utils.LavaFormatInfo("Reliability verified successfully!")
this is wrong, if there is a conflict it's a warning saying there is discrepancy, and if there isn't it should say verified successfully

2023-05-10 16:10 UTC, omerlavanet requested changes
critical fixes

2023-05-10 23:42 UTC, Yaroms commented on protocol/rpcconsumer/rpcconsumer_server.go
> +	relayRequestData := relayResult.Request.RelayData
need more info :)

2023-05-11 14:37 UTC, omerlavanet approved these changes

2023-05-12 07:03 UTC, omerlavanet approved these changes

2023-05-12 07:03 UTC, merged