Update Readme with Autocomplete Gist Link
lavanet/lava pull request #498
Opened 2023-05-18 03:50 UTC by KagemniKarimu

Added @oren-lava AutoComplete to Repo !

2023-05-18 14:33 UTC, SeanZoR approved these changes

2023-05-21 11:37 UTC, Yaroms approved these changes

2023-05-21 11:38 UTC, Yaroms requested changes
can you add the script to the folder "scripts" in our repo and update the readme?

2023-05-22 11:02 UTC, Yaroms approved these changes

2023-05-22 11:09 UTC, merged