Cns 551 create extended pairing to support the sdk
lavanet/lava pull request #675
Opened 2023-08-02 16:39 UTC by Yaroms

2023-08-02 16:43 UTC, ranlavanet requested changes

2023-08-02 16:43 UTC, ranlavanet commented on proto/lava/pairing/query.proto
> +  uint64 cu = 2;
max_cu would make more sense

2023-08-03 10:20 UTC, ranlavanet approved these changes

2023-08-03 10:47 UTC, oren-lava approved these changes

2023-08-03 10:53 UTC, omerlavanet approved these changes

2023-08-03 10:53 UTC, merged