Adjust Makefile for additional target lavad-protocol
lavanet/lava pull request #697
Opened 2023-08-09 17:37 UTC by orenl-lava

User must explicitly choose the target binaries, via the target(s) or using env-var LAVA_BINARY:

{build,install}-lavad: build/install lavad
{build,install}-lava-protocol: build/intsall lava-protocol
{build,install}-all: build/install all binaries
{build,install}: build/install $LAVA_BINARY (in env; error if unset)

2023-08-10 13:55 UTC, orenl-lava commented on Makefile
> +proto-gen: $(BUILDDIR)/proto-gen
something got messed up in your merge here - I will fix.

2023-08-10 13:55 UTC, orenl-lava commented on lava-protocol/main.go
should should be `cmd/lava-protocol/main.go` ... I will fix.

2023-08-10 14:29 UTC, ranlavanet submitted a review, later dismissed

2023-08-10 14:44 UTC, orenl-lava commented on lava-protocol/main.go
fixed 788bc0c

2023-08-10 14:44 UTC, orenl-lava commented on Makefile
> +proto-gen: $(BUILDDIR)/proto-gen
fixed 788bc0c

2023-08-10 14:48 UTC, ranlavanet submitted a review, later dismissed

2023-08-13 05:40 UTC, omerlavanet requested changes
If e2e builds we need to remove the build from the e2e workflow otherwise we build twice

2023-08-13 10:44 UTC, omerlavanet approved these changes

2023-08-13 13:21 UTC, merged