CNS-526: query delegator rewards
lavanet/lava pull request #774
Opened 2023-09-07 14:00 UTC by oren-lava

In this PR I've implemented the `delegator-rewards` query which allows a delegator to query for its unclaimed rewards. Also, using the optional `--provider` and `--chain-id` flags, the query's output can be filtered accordingly.
Finally, the unit tests of CNS-531 were updated to use this query

2023-09-11 17:07 UTC, orenl-lava requested changes

2023-09-11 17:07 UTC, orenl-lava commented on x/dualstaking/keeper/grpc_query_delegator_rewards.go
> +				rewards = append(rewards, reward)
unsure why there should be more than one match here?

2023-09-14 08:08 UTC, oren-lava commented on x/dualstaking/keeper/delegate.go
> +func (k Keeper) GetAllDelegations(ctx sdk.Context) []types.Delegation {
forgot to delete it (used for local testing). fixed, see https://github.com/lavanet/lava/commit/ae61adc692c2df4d45f7413b1b5e6cada96f134d

2023-09-14 08:09 UTC, oren-lava commented on proto/lavanet/lava/dualstaking/query.proto
> +  // Queries a provider for all its delegators.
done. see https://github.com/lavanet/lava/commit/ae61adc692c2df4d45f7413b1b5e6cada96f134d

2023-09-18 09:14 UTC, orenl-lava approved these changes

2023-09-20 08:53 UTC, merged