now cu will be the floor of the limit and the cu
lavanet/lava pull request #856
Opened 2023-10-04 11:00 UTC by Yaroms

2023-10-04 14:20 UTC, omerlavanet requested changes

2023-10-04 14:20 UTC, omerlavanet commented on x/pairing/keeper/limitConsumer.go
> +		return culimit - project.UsedCu, nil
needs to be in the current epoch

2023-10-05 10:18 UTC, Yaroms commented on x/pairing/keeper/limitConsumer.go
> +		return culimit - project.UsedCu, nil
done

2023-10-12 08:51 UTC, oren-lava approved these changes

2023-10-12 09:59 UTC, merged