CNS-662-add-etherium-verifications
lavanet/lava pull request #940
Opened 2023-11-02 13:59 UTC by Yaroms

2023-11-02 14:00 UTC, omerlavanet requested changes

2023-11-02 14:00 UTC, omerlavanet commented on cookbook/specs/spec_add_ethereum.json
> +                                "name": "trusted-rpc",
```suggestion
                                "name": "trustless-rpc",
```

2023-11-02 14:01 UTC, omerlavanet submitted a review, later dismissed

2023-11-05 09:48 UTC, shleikes approved these changes

2023-11-05 09:49 UTC, merged